<% if ( DOTCI_PULL_REQUEST ) { %>
skip: true
<% } %>

before_run: 'for file in `find . -type f -not -path "./.git/*"`; do touch -d "\$(git rev-list -n 1 HEAD \$file | xargs git show -s --format=%ai)" \$file; done'

run:
  master: '--daemon && sleep 180 && docker-compose ps'

after_each: 'docker rm -vf <% out<< JOB_NAME.toLowerCase().replaceAll('[^0-9a-z]','') %><% out<< BUILD_NUMBER %>_master_run_1'
