run:
  master: '--daemon && sleep 180 && docker-compose ps'

# https://github.com/docker/compose/issues/2791
after_each: 'docker rm -vf <% out<< JOB_NAME.toLowerCase().replaceAll('[^0-9a-z]','') %><% out<< BUILD_NUMBER %>_master_run_1'
